
prj_Info = list(
  original_nms     = c(df= "cric_olinknpx_112023_v1_sas7bdat", Rdata= "cric_olinknpx_112023_v1.Rdata"),
  complete_nms     = c(df= "df_complete", Rdata= "02-cric_complete112023.Rdata"), # in data folder
  add_vars_name    = "cric_add_variables.inc",  # In CRIC_prj folder
  tvars_mtx_name   = "cric_tvars_mtx.inc"    ,  # In CRIC_prj folder
  prj_learners     = "prj_learners.inc"
)  

  